---
- name: Verify
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: test connection
      ansible.builtin.ping:

    - name: try the package module
      ansible.builtin.package:
        name: gzip
        state: present
